modLoader="javafml"
loaderVersion="[47,)"
license="Public Domain"

[[mods]]
modId="hlmod"
version="5.0.0"
displayName="Max's Half-Life Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Maxwell, AKA krazykatkoder"
description="max's half life inspired mod"

[[dependencies.hlmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




