
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.hl.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.hl.item.XenianPocketDimensionItem;
import net.mcreator.hl.item.XenInstdiscItem;
import net.mcreator.hl.item.XenCrystalShardItem;
import net.mcreator.hl.item.Xen2Item;
import net.mcreator.hl.item.XENItem;
import net.mcreator.hl.item.UraniumingotItem;
import net.mcreator.hl.item.UraniumBoxItem;
import net.mcreator.hl.item.U235NuggetItem;
import net.mcreator.hl.item.TranquilizerDartItem;
import net.mcreator.hl.item.TauCannonItem;
import net.mcreator.hl.item.TauBulletItem;
import net.mcreator.hl.item.SteelslugShellItem;
import net.mcreator.hl.item.SteelSlugItem;
import net.mcreator.hl.item.SteelMIxItem;
import net.mcreator.hl.item.SteelIngotItem;
import net.mcreator.hl.item.Spas12Item;
import net.mcreator.hl.item.SpaceCoffeeItem;
import net.mcreator.hl.item.SnarkItem;
import net.mcreator.hl.item.ShotgunShellItem;
import net.mcreator.hl.item.ShotgunShellFullItem;
import net.mcreator.hl.item.SUITBATTERYItem;
import net.mcreator.hl.item.RocketLauncherItem;
import net.mcreator.hl.item.RPGROCKETItem;
import net.mcreator.hl.item.RPGFRAGMODItem;
import net.mcreator.hl.item.RPGFRAGItem;
import net.mcreator.hl.item.Pu256IngotItem;
import net.mcreator.hl.item.PlasticItem;
import net.mcreator.hl.item.PCVVestItem;
import net.mcreator.hl.item.NukeCoreItem;
import net.mcreator.hl.item.NineMMPistolItem;
import net.mcreator.hl.item.NeutroniumItem;
import net.mcreator.hl.item.Mp5casingItem;
import net.mcreator.hl.item.Mp5Item;
import net.mcreator.hl.item.MagnumRevolverItem;
import net.mcreator.hl.item.MagnumCasingItem;
import net.mcreator.hl.item.MagnumCartridgeItem;
import net.mcreator.hl.item.MagnumBulletItem;
import net.mcreator.hl.item.MP5BulletItem;
import net.mcreator.hl.item.M203SteelSlugModItem;
import net.mcreator.hl.item.M203SteelSlugItem;
import net.mcreator.hl.item.M203GrenadeItem;
import net.mcreator.hl.item.M203GrenadeAmmoItem;
import net.mcreator.hl.item.M203BuckShotModItem;
import net.mcreator.hl.item.M203BuckShotItem;
import net.mcreator.hl.item.LaserItem;
import net.mcreator.hl.item.KevlarArmorItem;
import net.mcreator.hl.item.IMPROBItem;
import net.mcreator.hl.item.IHATEYOUDiscItem;
import net.mcreator.hl.item.HORNETItem;
import net.mcreator.hl.item.HIVEHANDItem;
import net.mcreator.hl.item.HEVArmorItem;
import net.mcreator.hl.item.HEShellItem;
import net.mcreator.hl.item.GrenadeTexureItem;
import net.mcreator.hl.item.GrenadeItem;
import net.mcreator.hl.item.GluonGunItem;
import net.mcreator.hl.item.GluonFireItem;
import net.mcreator.hl.item.FragNadeItem;
import net.mcreator.hl.item.DetonatorItem;
import net.mcreator.hl.item.DadItemItem;
import net.mcreator.hl.item.CupItem;
import net.mcreator.hl.item.CrowbarItem;
import net.mcreator.hl.item.CrossbowItem;
import net.mcreator.hl.item.CoilItem;
import net.mcreator.hl.item.CoffeeItem;
import net.mcreator.hl.item.BulletItem;
import net.mcreator.hl.item.BuckshotItem;
import net.mcreator.hl.item.BuckShotShellItem;
import net.mcreator.hl.item.BoomBoxItem;
import net.mcreator.hl.item.BlackplasticItem;
import net.mcreator.hl.item.BlackMesaResearchFacilityItem;
import net.mcreator.hl.item.BatteryItem;
import net.mcreator.hl.item.ApotheiosisItem;
import net.mcreator.hl.HlmodMod;

public class HlmodModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, HlmodMod.MODID);
	public static final RegistryObject<Item> XEN = REGISTRY.register("xen", () -> new XENItem());
	public static final RegistryObject<Item> HEV_ARMOR_HELMET = REGISTRY.register("hev_armor_helmet", () -> new HEVArmorItem.Helmet());
	public static final RegistryObject<Item> HEV_ARMOR_CHESTPLATE = REGISTRY.register("hev_armor_chestplate", () -> new HEVArmorItem.Chestplate());
	public static final RegistryObject<Item> HEV_ARMOR_LEGGINGS = REGISTRY.register("hev_armor_leggings", () -> new HEVArmorItem.Leggings());
	public static final RegistryObject<Item> HEV_ARMOR_BOOTS = REGISTRY.register("hev_armor_boots", () -> new HEVArmorItem.Boots());
	public static final RegistryObject<Item> APOTHEIOSIS = REGISTRY.register("apotheiosis", () -> new ApotheiosisItem());
	public static final RegistryObject<Item> XEN_2 = REGISTRY.register("xen_2", () -> new Xen2Item());
	public static final RegistryObject<Item> XENGRASS = block(HlmodModBlocks.XENGRASS);
	public static final RegistryObject<Item> DAD_ITEM = REGISTRY.register("dad_item", () -> new DadItemItem());
	public static final RegistryObject<Item> XEN_CRYSTAL = block(HlmodModBlocks.XEN_CRYSTAL);
	public static final RegistryObject<Item> PCV_VEST_HELMET = REGISTRY.register("pcv_vest_helmet", () -> new PCVVestItem.Helmet());
	public static final RegistryObject<Item> PCV_VEST_CHESTPLATE = REGISTRY.register("pcv_vest_chestplate", () -> new PCVVestItem.Chestplate());
	public static final RegistryObject<Item> PCV_VEST_LEGGINGS = REGISTRY.register("pcv_vest_leggings", () -> new PCVVestItem.Leggings());
	public static final RegistryObject<Item> PCV_VEST_BOOTS = REGISTRY.register("pcv_vest_boots", () -> new PCVVestItem.Boots());
	public static final RegistryObject<Item> SUITBATTERY = REGISTRY.register("suitbattery", () -> new SUITBATTERYItem());
	public static final RegistryObject<Item> IMPROB = REGISTRY.register("improb", () -> new IMPROBItem());
	public static final RegistryObject<Item> KEVLAR_ARMOR_HELMET = REGISTRY.register("kevlar_armor_helmet", () -> new KevlarArmorItem.Helmet());
	public static final RegistryObject<Item> KEVLAR_ARMOR_CHESTPLATE = REGISTRY.register("kevlar_armor_chestplate", () -> new KevlarArmorItem.Chestplate());
	public static final RegistryObject<Item> KEVLAR_ARMOR_LEGGINGS = REGISTRY.register("kevlar_armor_leggings", () -> new KevlarArmorItem.Leggings());
	public static final RegistryObject<Item> KEVLAR_ARMOR_BOOTS = REGISTRY.register("kevlar_armor_boots", () -> new KevlarArmorItem.Boots());
	public static final RegistryObject<Item> W_33_WARHEAD = block(HlmodModBlocks.W_33_WARHEAD);
	public static final RegistryObject<Item> CROWBAR = REGISTRY.register("crowbar", () -> new CrowbarItem());
	public static final RegistryObject<Item> SPAS_12 = REGISTRY.register("spas_12", () -> new Spas12Item());
	public static final RegistryObject<Item> MP_5 = REGISTRY.register("mp_5", () -> new Mp5Item());
	public static final RegistryObject<Item> TAU_CANNON = REGISTRY.register("tau_cannon", () -> new TauCannonItem());
	public static final RegistryObject<Item> M_203_GRENADE = REGISTRY.register("m_203_grenade", () -> new M203GrenadeItem());
	public static final RegistryObject<Item> M_203_BUCK_SHOT_MOD = REGISTRY.register("m_203_buck_shot_mod", () -> new M203BuckShotModItem());
	public static final RegistryObject<Item> M_203_STEEL_SLUG_MOD = REGISTRY.register("m_203_steel_slug_mod", () -> new M203SteelSlugModItem());
	public static final RegistryObject<Item> GLUON_GUN = REGISTRY.register("gluon_gun", () -> new GluonGunItem());
	public static final RegistryObject<Item> NINE_MM_PISTOL = REGISTRY.register("nine_mm_pistol", () -> new NineMMPistolItem());
	public static final RegistryObject<Item> HIVEHAND = REGISTRY.register("hivehand", () -> new HIVEHANDItem());
	public static final RegistryObject<Item> MAGNUM_REVOLVER = REGISTRY.register("magnum_revolver", () -> new MagnumRevolverItem());
	public static final RegistryObject<Item> ROCKET_LAUNCHER = REGISTRY.register("rocket_launcher", () -> new RocketLauncherItem());
	public static final RegistryObject<Item> RPGFRAGMOD = REGISTRY.register("rpgfragmod", () -> new RPGFRAGMODItem());
	public static final RegistryObject<Item> SHOTGUN_SHELL_FULL = REGISTRY.register("shotgun_shell_full", () -> new ShotgunShellFullItem());
	public static final RegistryObject<Item> MP_5_BULLET = REGISTRY.register("mp_5_bullet", () -> new MP5BulletItem());
	public static final RegistryObject<Item> MAGNUM_CARTRIDGE = REGISTRY.register("magnum_cartridge", () -> new MagnumCartridgeItem());
	public static final RegistryObject<Item> RPGROCKET = REGISTRY.register("rpgrocket", () -> new RPGROCKETItem());
	public static final RegistryObject<Item> RPGFRAG = REGISTRY.register("rpgfrag", () -> new RPGFRAGItem());
	public static final RegistryObject<Item> M_203_GRENADE_AMMO = REGISTRY.register("m_203_grenade_ammo", () -> new M203GrenadeAmmoItem());
	public static final RegistryObject<Item> M_203_BUCK_SHOT = REGISTRY.register("m_203_buck_shot", () -> new M203BuckShotItem());
	public static final RegistryObject<Item> M_203_STEEL_SLUG = REGISTRY.register("m_203_steel_slug", () -> new M203SteelSlugItem());
	public static final RegistryObject<Item> XENIANMASS = block(HlmodModBlocks.XENIANMASS);
	public static final RegistryObject<Item> BUCKSHOT = REGISTRY.register("buckshot", () -> new BuckshotItem());
	public static final RegistryObject<Item> SHOTGUN_SHELL_EMPTY = REGISTRY.register("shotgun_shell_empty", () -> new ShotgunShellItem());
	public static final RegistryObject<Item> PLASTIC = REGISTRY.register("plastic", () -> new PlasticItem());
	public static final RegistryObject<Item> LASER = REGISTRY.register("laser", () -> new LaserItem());
	public static final RegistryObject<Item> COIL = REGISTRY.register("coil", () -> new CoilItem());
	public static final RegistryObject<Item> BATTERY = REGISTRY.register("battery", () -> new BatteryItem());
	public static final RegistryObject<Item> BLACKPLASTIC = REGISTRY.register("blackplastic", () -> new BlackplasticItem());
	public static final RegistryObject<Item> BULLET = REGISTRY.register("bullet", () -> new BulletItem());
	public static final RegistryObject<Item> MP_5CASING = REGISTRY.register("mp_5casing", () -> new Mp5casingItem());
	public static final RegistryObject<Item> URANIUMINGOT = REGISTRY.register("uraniumingot", () -> new UraniumingotItem());
	public static final RegistryObject<Item> NEUTRONIUM = REGISTRY.register("neutronium", () -> new NeutroniumItem());
	public static final RegistryObject<Item> U_235BLOCK = block(HlmodModBlocks.U_235BLOCK);
	public static final RegistryObject<Item> PU_239 = block(HlmodModBlocks.PU_239);
	public static final RegistryObject<Item> PU_256_INGOT = REGISTRY.register("pu_256_ingot", () -> new Pu256IngotItem());
	public static final RegistryObject<Item> U_235_NUGGET = REGISTRY.register("u_235_nugget", () -> new U235NuggetItem());
	public static final RegistryObject<Item> URANIUM_BOX = REGISTRY.register("uranium_box", () -> new UraniumBoxItem());
	public static final RegistryObject<Item> XEN_CRYSTAL_SHARD = REGISTRY.register("xen_crystal_shard", () -> new XenCrystalShardItem());
	public static final RegistryObject<Item> GRENADE_TEXURE = REGISTRY.register("grenade_texure", () -> new GrenadeTexureItem());
	public static final RegistryObject<Item> HE_SHELL = REGISTRY.register("he_shell", () -> new HEShellItem());
	public static final RegistryObject<Item> BUCK_SHOT_SHELL = REGISTRY.register("buck_shot_shell", () -> new BuckShotShellItem());
	public static final RegistryObject<Item> STEELSLUG_SHELL = REGISTRY.register("steelslug_shell", () -> new SteelslugShellItem());
	public static final RegistryObject<Item> NUKE_CORE = REGISTRY.register("nuke_core", () -> new NukeCoreItem());
	public static final RegistryObject<Item> MAGNUM_CASING = REGISTRY.register("magnum_casing", () -> new MagnumCasingItem());
	public static final RegistryObject<Item> MAGNUM_BULLET = REGISTRY.register("magnum_bullet", () -> new MagnumBulletItem());
	public static final RegistryObject<Item> STEEL_M_IX = REGISTRY.register("steel_m_ix", () -> new SteelMIxItem());
	public static final RegistryObject<Item> STEEL_INGOT = REGISTRY.register("steel_ingot", () -> new SteelIngotItem());
	public static final RegistryObject<Item> TAU_BULLET = REGISTRY.register("tau_bullet", () -> new TauBulletItem());
	public static final RegistryObject<Item> STEEL_SLUG = REGISTRY.register("steel_slug", () -> new SteelSlugItem());
	public static final RegistryObject<Item> HORNET = REGISTRY.register("hornet", () -> new HORNETItem());
	public static final RegistryObject<Item> GLUON_FIRE = REGISTRY.register("gluon_fire", () -> new GluonFireItem());
	public static final RegistryObject<Item> XENIAN_POCKET_DIMENSION = REGISTRY.register("xenian_pocket_dimension", () -> new XenianPocketDimensionItem());
	public static final RegistryObject<Item> COFFEE = REGISTRY.register("coffee", () -> new CoffeeItem());
	public static final RegistryObject<Item> CUP = REGISTRY.register("cup", () -> new CupItem());
	public static final RegistryObject<Item> SPACE_COFFEE = REGISTRY.register("space_coffee", () -> new SpaceCoffeeItem());
	public static final RegistryObject<Item> XENIUM_IDIODE = block(HlmodModBlocks.XENIUM_IDIODE);
	public static final RegistryObject<Item> BOOM_BOX = REGISTRY.register("boom_box", () -> new BoomBoxItem());
	public static final RegistryObject<Item> BLACK_MESA_RESEARCH_FACILITY = REGISTRY.register("black_mesa_research_facility", () -> new BlackMesaResearchFacilityItem());
	public static final RegistryObject<Item> GRENADE = REGISTRY.register("grenade", () -> new GrenadeItem());
	public static final RegistryObject<Item> SNARK = REGISTRY.register("snark", () -> new SnarkItem());
	public static final RegistryObject<Item> TRANQUILIZER_DART = REGISTRY.register("tranquilizer_dart", () -> new TranquilizerDartItem());
	public static final RegistryObject<Item> CROSSBOW = REGISTRY.register("crossbow", () -> new CrossbowItem());
	public static final RegistryObject<Item> SATCHEL = block(HlmodModBlocks.SATCHEL);
	public static final RegistryObject<Item> DETONATOR = REGISTRY.register("detonator", () -> new DetonatorItem());
	public static final RegistryObject<Item> IHATEYOU_DISC = REGISTRY.register("ihateyou_disc", () -> new IHATEYOUDiscItem());
	public static final RegistryObject<Item> XEN_INSTDISC = REGISTRY.register("xen_instdisc", () -> new XenInstdiscItem());
	public static final RegistryObject<Item> FRAG_NADE = REGISTRY.register("frag_nade", () -> new FragNadeItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
